### ISSUE TITLE
no disk usage

### ISSUE THREAD

**Issue by lgg** [Alanaktion/php-landing#7]
![image](https://cloud.githubusercontent.com/assets/12018713/18410248/6c837c74-7765-11e6-9d38-2573de50e371.png)

DigitalOcean VPS, 1 disk 20gb ssd no info for this ;(

maybe it refers to #6 ?

**Comment by Alanaktion** [comment]
It should work fine as-is on almost all systems. The idea with #6 was to show individual usage for all disks (for servers with more than one disk), but the current code should work fine.
What is the output of `\df -P` on your server?

**Comment by lgg** [comment]
@Alanaktion 
![image](https://cloud.githubusercontent.com/assets/12018713/18415217/42a7c14c-77f3-11e6-8176-c49a28844d0c.png)

**Comment by lgg** [comment]
maybe this is a cause: 
![image](https://cloud.githubusercontent.com/assets/12018713/18415234/d6baee18-77f3-11e6-83a5-1f51c80e61fe.png)


```
root@lgg:~# which sed
/bin/sed
root@lgg:~# which grep
/bin/grep
root@lgg:~# which df
/bin/df
```
